pipeline
{

agent any
 stages {
 
   stage('PULL') {

   steps {
   
   script {

checkout([$class: 'GitSCM', branches: [[name: '*/master']],

userRemoteConfigs: [[ url: 'https://github.com/baha2597/LC.git' ]]])



}
}
}

 stage('npm-Install') {
             steps{
                script{
                    sh "npm install"
                }
            }
        }
        
stage('build') {
steps{

script {

sh "ansible-playbook Ansible/build.yml -i Ansible/Inventory/host.yml "

}
}
} 
        
stage('docker')
{
                  steps {
                         script{
                         sh "ansible-playbook Ansible/docker.yml -i Ansible/inventory/host.yml "
                                }
                        }
  } 
      


}
}
